# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['date'], 'verbose_name': 'Изображение'},
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', null=True, upload_to='', width_field='photo_width'),
        ),
    ]
