# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180613_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', null=True, upload_to='photos/', width_field='photo_width'),
        ),
    ]
