# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180614_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, height_field='300', null=True, upload_to='', width_field='500'),
        ),
    ]
