# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_photo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_height',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_width',
            field=models.IntegerField(default=300),
        ),
    ]
