# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20180615_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field='photo_height', upload_to='', width_field='photo_width'),
        ),
    ]
