# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20180615_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_width',
            field=models.IntegerField(default=0),
        ),
    ]
