# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180615_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
